-- AlterTable
ALTER TABLE "SiteSetting" ADD COLUMN     "pointsLevel3" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "pointsLevel4" INTEGER NOT NULL DEFAULT 300,
ADD COLUMN     "pointsLevel5" INTEGER NOT NULL DEFAULT 800,
ADD COLUMN     "pointsLevel6" INTEGER NOT NULL DEFAULT 2000;
