import { test, expect } from "./fixtures";

test("发帖校验失败保留草稿，成功后清空，切换账号隔离草稿", async ({ page }) => {
  await page.goto("/login");
  await page.fill('[name="email"]', "admin@example.com");
  await page.fill('[name="password"]', "ReleaseAdmin123!");
  await page.getByRole("button", { name: "登录 →" }).click();
  await expect(page.locator("header")).toContainText("admin");
  await page.goto("/c/tech/new");
  const title = page.locator('[name="title"]');
  const content = page.locator('textarea[name="content"]');
  await expect(page.locator('input[name="cf-turnstile-response"]')).not.toHaveValue("");
  await title.fill("短标题");
  await title.evaluate((element: HTMLInputElement) => { element.minLength = 1; });
  await content.fill("提交失败也要保留的正文");
  await page.getByRole("button", { name: "发布", exact: true }).click();
  await expect(page).toHaveURL(/error=invalid/);
  await expect(title).toHaveValue("短标题");
  await expect(content).toHaveValue("提交失败也要保留的正文");
  await page.reload();
  await expect(content).toHaveValue("提交失败也要保留的正文");
  const uniqueTitle = `上线回归主题-${Date.now()}`;
  await title.fill(uniqueTitle);
  await page.getByRole("button", { name: "发布", exact: true }).click();
  await expect(page.getByRole("heading", { name: uniqueTitle })).toBeVisible();
  await page.goto("/c/tech/new");
  await expect(title).toHaveValue("");
  await expect(content).toHaveValue("");
  await content.fill("管理员的私有草稿");
  await page.getByRole("button", { name: "退出" }).first().click();
  await expect(page.locator("header").getByRole("link", { name: "登录" })).toBeVisible();
  const username = `draft${Date.now()}`;
  await page.goto("/register");
  await page.fill('[name="email"]', `${username}@test.dev`);
  await page.fill('[name="username"]', username);
  await page.fill('[name="password"]', "ForumTest123!");
  await page.getByRole("button", { name: /注册/ }).click();
  await expect(page.locator("header")).toContainText(username);
  await page.goto("/c/tech/new");
  await expect(content).toHaveValue("");
});

test("私信校验失败保留正文，中文输入法不误发送，提及与发送可用", async ({ page }) => {
  const username = `msg${Date.now()}`;
  await page.goto("/register");
  await page.fill('[name="email"]', `${username}@test.dev`);
  await page.fill('[name="username"]', username);
  await page.fill('[name="password"]', "ForumTest123!");
  await page.getByRole("button", { name: /注册/ }).click();
  await expect(page.locator("header")).toContainText(username);
  await page.goto("/messages/admin");
  const content = page.getByRole("textbox", { name: "私信内容" });
  await content.fill("傻逼");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  await expect(page).toHaveURL(/error=sensitive/);
  await expect(content).toHaveValue("傻逼");
  await content.fill("中文输入法测试");
  await content.dispatchEvent("keydown", { key: "Enter", isComposing: true });
  await expect(content).toHaveValue("中文输入法测试");
  await page.reload();
  await expect(content).toHaveValue("中文输入法测试");
  await content.fill("你好 @ad");
  await page.locator(".mention-item").filter({ hasText: "@admin" }).click();
  await expect(content).toHaveValue("你好 @admin ");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  await expect(content).toHaveValue("");
  await expect(page.locator(".post-content")).toContainText("你好 @admin");
  await page.reload();
  await expect(content).toHaveValue("");
});
